services:
  app:
    build: .
    container_name: hamgamplastic-app-1
    env_file:
      - ./Back-end/.env
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    container_name: hamgamplastic-mongodb-1
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data: